base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:

  odom_topic: /mobile_base_controller/odom
  map_frame: map
    
  # Trajectory
  
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 5.0
  feasibility_check_no_poses: 5
  global_plan_viapoint_sep: 1.0
  min_samples: 5
  exact_arc_length: True
  allow_init_with_backwards_motion: false

  # Robot
  
  max_vel_x: 0.3
  max_vel_x_backwards: 0.1
  max_vel_theta: 0.5
  acc_lim_x: 0.3
  acc_lim_theta: 0.4
  is_footprint_dynamic: true
  footprint_model:
    type: "line"
    line_start: [0.0, 0.0]
    line_end:   [-0.35, 0.0]

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.3
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  inflation_dist: 0.5

  ## Costmap converter plugin (optional)
  # costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull" # no visible improvement
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
    
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 10
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 500
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_inflation: 5.0
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet
  weight_viapoint: 0.75

  # Homotopy Class Planner

  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
