# Independent settings for the planner's costmap
global_costmap:
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: stvl_rgbd_layer
      type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
