slam_karto:
  base_frame: base_footprint

  # Scans:
  minimum_travel_distance: 0.2
  minimum_travel_heading : !degrees 10.0
  range_threshold        : 5.0
  use_scan_barycenter    : true
  resolution             : 0.05

  # .wav file to be played for audio loop-closure feedback
  loop_closure_audio_feedback_file: "fanfare_x.wav"

  # overloading some params of pal_karto/config/karto.yaml
  loop_search_maximum_distance        : 4.0
  loop_search_minimum_graph_distance  : 4
  loop_match_minimum_chain_size       : 5.0
  loop_match_minimum_response_coarse  : 0.7
  loop_match_minimum_response_fine    : 0.8
  loop_search_space_dimension         : 5.0
  link_scan_maximum_distance          : 5.0

  # overloading some params of pal_karto/config/scan_matcher.yaml
  correlation_search_space_smear_deviation: 0.02
