slam_toolbox:
  # Plugin params
  solver_plugin: solver_plugins::CeresSolver
  ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
  ceres_preconditioner: SCHUR_JACOBI
  ceres_trust_strategy: LEVENBERG_MARQUARDT
  ceres_dogleg_type: TRADITIONAL_DOGLEG
  ceres_loss_function: None

  # ROS Parameters
  odom_frame: odom
  map_frame: map
  base_frame: base_footprint
  scan_topic: /rgbd_scan
  mode: mapping #localization

  # if you'd like to immediately start continuing a map at a given pose
  # or at the dock, but they are mutually exclusive, if pose is given
  # will use pose
  #map_file_name: test_steve
  #map_start_pose: [0.0, 0.0, 0.0]
  #map_start_at_dock: true

  debug_logging: false
  throttle_scans: 1
  transform_publish_period: 0.05 #if 0 never publishes odometry
  map_update_interval: 1.0
  resolution: 0.05
  max_laser_range: 20.0 #for rastering images
  minimum_time_interval: 0.5
  transform_timeout: 0.2
  tf_buffer_duration: 30.
  stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
  enable_interactive_mode: true

  # General Parameters
  use_scan_matching: true
  use_scan_barycenter: true
  minimum_travel_distance: 0.2
  minimum_travel_heading: !degrees 10.0
  scan_buffer_size: 60
  scan_buffer_maximum_scan_distance: 10
  link_match_minimum_response_fine: 0.4
  link_scan_maximum_distance: 8.0
  do_loop_closing: true
  loop_match_minimum_chain_size: 5
  loop_match_maximum_variance_coarse: 0.9
  loop_match_minimum_response_coarse: 0.6
  loop_match_minimum_response_fine: 0.5

  # Correlation Parameters - Correlation Parameters
  correlation_search_space_dimension: 0.3
  correlation_search_space_resolution: 0.01
  correlation_search_space_smear_deviation: 0.02

  # Correlation Parameters - Loop Closure Parameters
  loop_search_maximum_distance: 10.0
  loop_search_space_dimension: 5.0
  loop_search_space_resolution: 0.05
  loop_search_space_smear_deviation: 0.03

  # Scan Matcher Parameters
  distance_variance_penalty: 0.3
  angle_variance_penalty: 0.121839781

  fine_search_angle_offset: 0.00349066
  coarse_search_angle_offset: 0.34906585
  coarse_angle_resolution: 0.03490659
  minimum_angle_penalty: 0.9
  minimum_distance_penalty: 0.5
  use_response_expansion: false
