base_local_planner: robotino_local_planner/RobotinoLocalPlanner

RobotinoLocalPlanner:
  heading_lookahead: 1.0
  num_window_points: 10

  max_linear_vel: 0.3
  min_linear_vel: 0.025

  max_rotation_vel: 0.6
  min_rotation_vel: 0.1

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
